name: Deploy to Nekoweb
description: Deploy to Nekoweb using the Nekoweb API
author: fairfruit
inputs: 
  API_KEY:
    description: API key for Nekoweb
    required: true
  BUILD_DIR:
    description: Local build directory to deploy
    required: true
    default: /build
  DEPLOY_DIR:
    description: Remote directory to deploy to
    required: true
    default: /
  NEKOWEB_PAGENAME:
    description: Your NekoWeb page name (your username unless you use a custom domain).
    required: true
  CLEANUP:
    description: Also delete remote files that don't exist locally
    default: 'False'
  DELAY:
    description: Delay between Nekoweb API requests (in seconds)
    required: false
  RETRY_ATTEMTPS:
    description: Number of times to retry the Nekoweb API request
    required: false
  RETRY_DELAY:
    description: Delay between Nekoweb API request retries (in seconds) when rate limited
    required: false
  RETRY_EXP_BACKOFF:
    description: Exponential backoff for Nekoweb API request retries
    required: false
  ENCRYPTION_KEY:
      description: A secret key used to encrypt the file states. Must be a 32-byte URL-safe base64-encoded string
      required: false
  DEBUG:
      description: Enable debug mode
      required: false
branding:
  icon: upload-cloud
  color: blue
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Cleanup and deploy
      run: |
        CMD="python ${{ github.action_path }}/deploy.py ${{ inputs.API_KEY }} ${{ inputs.BUILD_DIR }} ${{ inputs.DEPLOY_DIR }} ${{ inputs.CLEANUP }} ${{ inputs.NEKOWEB_PAGENAME }}"
        if [[ -n "${{ inputs.DELAY }}" ]]; then
          CMD="$CMD --delay ${{ inputs.DELAY }}"
        fi
        if [[ -n "${{ inputs.ENCRYPTION_KEY }}" ]]; then
          CMD="$CMD --encryption-key ${{ inputs.ENCRYPTION_KEY }}"
        fi
        if [[ -n "${{ inputs.RETRY_ATTEMPTS }}" ]]; then
          CMD="$CMD --retry-attempts ${{ inputs.RETRY_ATTEMPTS }}"
        fi
        if [[ -n "${{ inputs.RETRY_DELAY }}" ]]; then
          CMD="$CMD --retry-delay ${{ inputs.RETRY_DELAY }}"
        fi
        if [[ -n "${{ inputs.RETRY_EXP_BACKOFF }}" =~ ^(true|True|TRUE)$ ]]; then
          CMD="$CMD --retry-exp-backoff"
        fi
        if [[ "${{ inputs.DEBUG }}" =~ ^(true|True|TRUE)$ ]]; then
          CMD="$CMD --debug"
        fi
        echo "Running command: $CMD"
        $CMD
      shell: bash
